### ISSUE TITLE
Is that any way to read the signal format settings of the device?

### ISSUE THREAD

**Issue by wilsonlmh** [Dev1an/Atem#5]
Is that any way to read the signal format(e.g. 1080/60i) settings of the device? Thanks!

**Comment by Dev1an** [comment]
Yes it is possible, but not so user friendly yet 😉.
For the moment you should listen for events with the name `"VidM"` the corresponding data is a buffer with binary data that you will have to parse in order to get the current video mode. The binary data is structured as follows: 
<img width="1024" alt="vmc-atem" src="https://user-images.githubusercontent.com/3158324/36143985-f5b2a9c0-10ac-11e8-8bb7-55301b22b07a.png">
(see [skarhoj's protocol specification](http://skaarhoj.com/fileadmin/BMDPROTOCOL.html) for all raw commands)

If you wrote your parsing code, feel free to contribute it back to the community by adding your code to this library and to file a "pull request".
If you don't know where to put your code have a look at the implementation for the following commands:
- [previewBus](http://dev1an.github.io/Atem/index.js.html#line746)
- [programBus](http://dev1an.github.io/Atem/index.js.html#line760)
- [auxiliaryOutput](http://dev1an.github.io/Atem/index.js.html#line772)

Feel free to ask further and reopen this issue if anything is unclear.
